# Generated by Django 4.1 on 2022-10-18 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DetailsForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_product', models.CharField(max_length=150)),
                ('price_of_product', models.CharField(max_length=150)),
                ('manufature_of_product', models.CharField(max_length=150)),
                ('rating', models.IntegerField()),
                ('reviews', models.CharField(max_length=150)),
            ],
        ),
    ]
