# Generated by Django 4.1 on 2022-10-19 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanpdealpage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=80)),
                ('issue', models.CharField(max_length=500)),
            ],
        ),
    ]
